# Config file for automatic testing at travis-ci.org

language: python

sudo: false

python:
    - "3.6"
    - "3.5"
    - "3.4"
    - "3.3"
    - "2.7"

before_install:
    - pip install -r requirements-dev.txt

install:
    - pip install -e .
    - pip install codecov==2.0.5

script:
    - coverage run --source=pytest_pipeline `which py.test` --flake8 tests pytest_pipeline

after_success:
    - coverage report -m
    - codecov
