# Config file for automatic testing at travis-ci.org

notifications:
    email: false

language: python

python:
    - "2.7"

before_install:
    - "pip install -r requirements.txt -r requirements-dev.txt"

install:
    - "python setup.py install"

script:
    - "py.test -v tests"
